version: '3.8'

services:
  base:
    build:
      context: ./base
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  webserver:
    build:
      context: ./services/webserver
    ports:
      - "8080:8080"
    depends_on:
      - base
  
  db:
    build:
      context: ./services/db
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydatabase
  
  scheduler:
    build:
      context: ./services/scheduler
    depends_on:
      - db
  logs:
    build:
      context: ./services/logs
    depends_on:
      - db
